# Generated by Django 6.1.1 on 2026-09-07 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('recurrence_days', models.PositiveIntegerField(blank=True, help_text='Repeat every N days (e.g. 1=daily, 7=weekly). Leave blank for a one-off chore.', null=True)),
                ('due_date', models.DateField()),
                ('assigned_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chores', to='chores.member')),
            ],
        ),
    ]
