# Generated by Django 6.1.1 on 2026-09-07 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_completionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='completionlog',
            name='chore_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='completionlog',
            name='chore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions', to='chores.chore'),
        ),
    ]
