# Generated by Django 6.1.1 on 2026-09-07 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_completionlog_chore_title_alter_completionlog_chore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='recurrence_days',
            field=models.PositiveIntegerField(blank=True, help_text='Repeat every N days (e.g. 1=daily, 7=weekly). Leave blank for a one-off chore.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
